(()=>{'use strict';
const asset='UCVhGR9TU1vfvHXl73uaEiEQ-irl-ideation-2026-09/';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');
let page=0;const cards=$$('.idea');
function filter(reset=true){clearTimeout(debounce);if(reset)page=0;const q=$('#idea-search').value.trim().toLowerCase(),f=$('#family-filter').value,e=$('#evidence-filter').value,n=Number($('#page-size').value);const found=cards.filter(c=>(!q||c.dataset.search.includes(q)||c.id==='idea-'+q.replace('#',''))&&(!f||c.dataset.family===f)&&(!e||c.dataset.covered===String(e==='covered')));const pages=Math.max(1,Math.ceil(found.length/n));page=Math.min(page,pages-1);cards.forEach(c=>c.hidden=true);found.slice(page*n,(page+1)*n).forEach(c=>c.hidden=false);$('#idea-count').textContent=found.length+' of 100 ideas'+(found.length?' · showing '+(page*n+1)+'–'+Math.min((page+1)*n,found.length):' · try a different search');$('#page-label').textContent='Page '+(page+1)+' of '+pages;$('#prev-page').disabled=page===0;$('#next-page').disabled=page===pages-1;}
let debounce;$('#idea-search').addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(()=>filter(),140)});['#family-filter','#evidence-filter','#page-size'].forEach(s=>$(s).addEventListener('change',()=>filter()));$('#prev-page').onclick=()=>{page--;filter(false);$('#thumbnail-gallery').scrollIntoView()};$('#next-page').onclick=()=>{page++;filter(false);$('#thumbnail-gallery').scrollIntoView()};
function revealHash(){clearTimeout(debounce);const match=location.hash.match(/^#idea-(\d+)$/);if(!match)return;const card=document.getElementById('idea-'+match[1]);if(!card)return;if(card.classList.contains('solo-video')){card.querySelector('.solo-brief').open=true;requestAnimationFrame(()=>card.scrollIntoView({block:'start'}));return;}$('#idea-search').value='';$('#family-filter').value='';$('#evidence-filter').value='';page=Math.floor(cards.indexOf(card)/Number($('#page-size').value));filter(false);requestAnimationFrame(()=>card.scrollIntoView({block:'start'}));}
filter();revealHash();window.addEventListener('hashchange',revealHash);
const chapters=$$('main>.chapter'),nav=$$('.chapter-nav a');let ticking=false;window.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{let active=chapters[0];chapters.forEach(c=>{if(c.getBoundingClientRect().top<150)active=c});nav.forEach(a=>a.setAttribute('aria-current',String(a.hash==='#'+active.id)));ticking=false})},{passive:true});nav[0].setAttribute('aria-current','true');
const modal=$('#thumbnail-modal');let thumbIndex=0,opener;
function showThumb(index){thumbIndex=(index+100)%100;const card=cards[thumbIndex],link=card.querySelector('[data-thumbnail-id]');$('#thumbnail-title').textContent='#'+(thumbIndex+1)+' · '+card.querySelector('h3').textContent;$('#thumbnail-full').src=link.href;$('#thumbnail-full').alt=card.querySelector('.generated-thumb img').alt;$('#thumbnail-download').href=link.href.split('?')[0];$('#thumbnail-download').download=link.href.split('/').pop().split('?')[0];if(!modal.open)modal.showModal();}
$$('[data-thumbnail-id]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();opener=a;showThumb(Number(a.dataset.thumbnailId)-1)}));$('#thumbnail-prev').onclick=()=>showThumb(thumbIndex-1);$('#thumbnail-next').onclick=()=>showThumb(thumbIndex+1);modal.addEventListener('close',()=>opener?.focus({preventScroll:true}));modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});document.addEventListener('keydown',e=>{if(!modal.open)return;if(e.key==='ArrowRight'){e.preventDefault();showThumb(thumbIndex+1)}if(e.key==='ArrowLeft'){e.preventDefault();showThumb(thumbIndex-1)}});
let data,current,chartWidth=1000;
function ratioAt(sec){const p=sec/current.durationSec*100,arr=current.curve;if(p<=arr[0].p)return arr[0].w;for(let i=1;i<arr.length;i++){if(arr[i].p>=p){const a=arr[i-1],b=arr[i];return a.w+(b.w-a.w)*(p-a.p)/(b.p-a.p)}}return arr.at(-1).w;}
function selectTime(sec,index=-1){$('#retention-time').value=sec;const ratio=ratioAt(sec);$('#retention-readout').textContent=time(sec)+' · '+(ratio*100).toFixed(1)+'% watch ratio (interpolated)';$('#retention-watch').href='https://www.youtube.com/watch?v='+current.videoId+'&t='+Math.floor(sec)+'s';const x=40+sec/current.durationSec*(chartWidth-55);$('#chart-cursor').setAttribute('x1',x);$('#chart-cursor').setAttribute('x2',x);$$('.moment').forEach((m,i)=>m.dataset.selected=String(i===index));}
function drawVideo(){current=data.retention.cases.find(v=>v.videoId===$('#retention-select').value)||data.retention.cases[0];$('#retention-time').max=current.durationSec;$('#retention-stats').innerHTML=[['Length',time(current.durationSec)],['At 5s',(ratioAt(5)*100).toFixed(1)+'%'],['At 15s',(ratioAt(15)*100).toFixed(1)+'%'],['At 30s',(ratioAt(30)*100).toFixed(1)+'%']].map(([label,value])=>'<div><b>'+esc(value)+'</b><span>'+esc(label)+'</span></div>').join('');
 chartWidth=Math.max(280,Math.min(1000,$('#retention-chart').clientWidth));$('#retention-chart').setAttribute('viewBox','0 0 '+chartWidth+' 330');
 const ymax=Math.max(1.1,...current.curve.map(p=>p.w)),X=p=>40+p/100*(chartWidth-55),Y=w=>285-w/ymax*255;let svg='<title id="chart-title">'+esc(current.title)+' audience retention</title><desc id="chart-desc">Measured watch ratio by elapsed time. Select a timestamp using the slider or moment buttons below.</desc>';
 for(const r of [0,.25,.5,.75,1]){svg+='<line class="grid" x1="40" x2="'+(chartWidth-15)+'" y1="'+Y(r)+'" y2="'+Y(r)+'"/><text x="34" y="'+(Y(r)+5)+'" text-anchor="end">'+Math.round(r*100)+'%</text>'}
 for(const p of [0,25,50,75,100]){svg+='<text x="'+X(p)+'" y="316" text-anchor="'+(p===0?'start':p===100?'end':'middle')+'">'+time(current.durationSec*p/100)+'</text>'}
 svg+='<path class="curve" d="'+current.curve.map((p,i)=>(i?'L':'M')+X(p.p).toFixed(2)+','+Y(p.w).toFixed(2)).join(' ')+'"/>';
 current.moments.forEach(m=>{const sec=Math.min(m.sec,current.durationSec);svg+='<circle cx="'+X(sec/current.durationSec*100)+'" cy="'+Y(ratioAt(sec))+'" r="5" fill="'+(m.kind==='peak'?'#7de0b3':'#ff9292')+'"><title>'+esc(m.t+' '+m.kind+': '+m.what)+'</title></circle>'});
 svg+='<line id="chart-cursor" x1="55" x2="55" y1="20" y2="285" stroke="#ffd676" stroke-width="2" stroke-dasharray="5 5"/>';$('#retention-chart').innerHTML=svg;$('#retention-source').href=current.source_page;
 $('#moment-list').innerHTML=current.moments.map((m,i)=>'<article class="moment"><button class="'+esc(m.kind)+'" data-moment="'+i+'">'+esc(m.t)+' · '+(m.kind==='peak'?'Peak':'Drop')+'</button><div><p><span class="label">Measured / source-reported signal</span>'+esc(m.what)+'</p><p><span class="label">Source annotation, not a causal finding</span>'+esc(m.annotation||'No semantic annotation supplied.')+'</p><p><span class="label">Proposed edit to test</span>'+esc(m.proposed_edit)+'</p></div></article>').join('');$$('[data-moment]').forEach(b=>b.onclick=()=>selectTime(current.moments[Number(b.dataset.moment)].sec,Number(b.dataset.moment)));selectTime(0);window.__retentionCurrent=current;}
$('#retention-time').addEventListener('input',e=>{if(current)selectTime(Number(e.target.value))});$('#retention-select').addEventListener('change',()=>{if(data)drawVideo()});
window.addEventListener('resize',()=>{if(data){const sec=Number($('#retention-time').value);drawVideo();selectTime(sec)}});
fetch(asset+'strategy-data.json?v=seven-sections-v1').then(r=>{if(!r.ok)throw Error('Research load failed');return r.json()}).then(d=>{data=d;drawVideo();window.__studyData=d}).catch(()=>{$('#moment-list').innerHTML='<p class="gap">The chart data could not load. Reload or use the linked channel analysis above.</p>'});
})();
