import json,html,re,statistics,shutil
from pathlib import Path
BASE=Path(__file__).resolve().parent;REPO=BASE.parents[2]
SLUG='UCVhGR9TU1vfvHXl73uaEiEQ-irl-ideation-2026-09';A=REPO/'studies'/SLUG
D=json.loads((A/'strategy-data.json').read_text(encoding='utf8'));M=json.loads((A/'thumbnail-manifest.json').read_text(encoding='utf8'));TH={i['id']:i for i in M['items']}
E={i['video_id']:i for i in D['evidence_pool']};H=lambda x:html.escape(str(x),quote=True)
def fmt(n):return f'{n/1e6:.2f}M' if n>=1e6 else f'{n/1000:.0f}K' if n>=1000 else str(n)
def money(n):return '$'+f'{n:,}'
def thumb(e):return SLUG+'/thumbs/'+e['video_id']+'.jpg' if (A/'thumbs'/(e['video_id']+'.jpg')).exists() else e['thumbnail']
def evidence(e):
 score=e.get('lift'); view=e.get('source_views') or e.get('views_lifetime') or e.get('views_first_28_days'); status='Outlier ≥2×' if score and score>=2 else 'Above baseline' if score and score>1 else 'At/below baseline' if score is not None else 'Unscored'
 return f'<li class="evidence"><a href="{H(e["url"])}" target="_blank" rel="noopener"><img src="{H(thumb(e))}" loading="lazy" width="160" height="90" alt="Source thumbnail for {H(e["title"])}"></a><div><a href="{H(e["url"])}" target="_blank" rel="noopener">{H(e["title"])}</a><p>{H(e["channel"])} · <b>{f"{score:.2f}×" if score is not None else "Unscored"}</b> · {status}</p><small>{fmt(view)+" source views · " if view else ""}{H(e.get("published",""))}<br>{H(e["basis"])}<br>{H(e.get('relevance','Original reference set.'))}</small></div></li>'
def refs(arr):return '<ul class="evidence-list">'+''.join(evidence(e) for e in arr)+'</ul>' if arr else '<p class="gap">No direct scored match in the searched catalogue. Treat this as an experiment.</p>'
def cover(i,axis):
 n=i['coverage'][axis]
 return f'<span class="badge {"good" if n>=2 else "gap"}">{axis.title()}: {n} channel{"s" if n!=1 else ""} with ≥2× examples</span>'
def card(i):
 id=i['id'];t=TH[id];p=D['profiles'][i['production_profile']];r=i['reference'];ref=E.get(r['reference_id'])
 oldwhy=i['why'].replace('—',': ')
 intro=''.join(f'<li><b>{label}</b><span>{H(s)}</span></li>' for label,s in zip(['0 (First Frame)–5s','5s–15s','15s–30s'],i['intro']))
 image=f'{SLUG}/{t["image"]}';preview=f'{SLUG}/{t["preview"]}'
 revision='Reference-based revision' if t.get('revision')=='composition-v3' else 'Existing concept'
 return f'''<article class="idea" id="idea-{id}" data-family="{H(i['family'])}" data-search="{H((i['title']+' '+i['ingredients']+' '+i['title_shape']).lower())}" data-covered="{str(min(i['coverage'].values())>=2).lower()}">
 <a class="thumb generated-thumb" data-thumbnail-id="{id}" href="{image}?v={t['sha256'][:12]}" aria-label="Enlarge thumbnail for {H(i['title'])}"><img src="{preview}?v={t['sha256'][:12]}" width="640" height="360" loading="lazy" alt="Niz thumbnail concept: {H(i['title'])}"></a>
 <div class="idea-body"><div class="eyebrow">{id:03} / {H(i['family'])}</div><h3>{H(i['title'])}</h3><p class="idea-summary">{H(i['summary'])}</p><ol class="intro">{intro}</ol>
 <div class="idea-meta"><a href="#cost-{i['production_profile']}">{money(p['low'])}–{money(p['high'])} base shoot</a><a href="{image}" download>Download JPG</a></div>
 <details class="why"><summary>Why this Idea</summary><div class="equation"><span>Title shape</span><b>{H(i['title_shape'])}</b><span>+ Content ingredients</span><b>{H(i['ingredients'])}</b><span>= Proposed title</span><b>{H(i['title'])}</b></div>
 <p class="fine">The ingredients are combined with this shape as a creative hypothesis. The exact Niz episode has not been tested.</p><h4>Title-shape evidence</h4>{cover(i,'shape')}<p class="fine">{H(i['shape_scope'])}</p>{refs(i['shape_evidence'])}<h4>Content-ingredient evidence</h4>{cover(i,'ingredient')}<p class="fine">{H(i['ingredient_scope'])}</p>{refs(i['ingredient_evidence'])}
 <details><summary>Original rationale and reference set</summary><p>{H(oldwhy)}</p><p class="fine">Original September 10 hypothesis; historical figures may differ from the newer nearby-upload baselines above.</p>{refs(i['evidence'])}</details></details>
 <details class="comparison"><summary>Thumbnail: source → Niz</summary><div class="compare-pair"><figure><a href="https://www.youtube.com/watch?v={r['reference_id']}" target="_blank" rel="noopener"><img src="{SLUG}/thumbs/{r['reference_id']}.jpg" width="320" height="180" loading="lazy" alt="Composition reference"></a><figcaption>{H(r['reference_channel'])}: {H(r['reference_title'])}</figcaption></figure><figure><img src="{preview}" width="320" height="180" loading="lazy" alt="Niz adaptation"><figcaption>{revision} · concept #{id}</figcaption></figure></div><p>{H(r['adaptation'])}</p><p class="fine">Keep the source framing and visual hierarchy; change the creator and episode-specific subject. AI cast and scenes need real shoot references before final packaging.</p></details>
 <p class="fine">{H(p['days'])} · {H(p['crew'])}{' · '+H(i['spend_note']) if i['spend_note'] else ''}</p></div></article>'''

from solo_sections import solo_sections
solo_ideation,solo_creative,solo_production,solo_data=solo_sections(A,SLUG)

families=list(dict.fromkeys(i['family'] for i in D['ideas']))
ideation=f'''<section id="ideation" class="chapter"><div class="section-head"><div><span class="eyebrow">01 / Develop the episode</span><h2>Ideation</h2></div><p>125 ideas. Including 25 new briefs Niz can film alone.</p></div>{solo_ideation}<h3 id="original-ideas">Original 100 ideas and thumbnails</h3>
 <div id="thumbnail-gallery" class="toolbar"><label>Find an original idea<input id="idea-search" type="search" placeholder="Try Rex, food, $1 or Morocco"></label><label>Family<select id="family-filter"><option value="">All 10 families</option>{''.join(f'<option>{H(f)}</option>' for f in families)}</select></label><label>Evidence<select id="evidence-filter"><option value="">All ideas</option><option value="covered">2+ outlier channels on both axes</option><option value="gaps">Evidence gaps to test</option></select></label><label>Show<select id="page-size"><option value="10">10 at a time</option><option value="100">All 100</option></select></label></div>
 <div class="result-bar"><p id="idea-count" role="status">100 ideas</p><a href="{SLUG}/nizarisaqtirl-100-thumbnails.zip" download>Download all 100 thumbnails ↓</a></div><p class="fine">An outlier here means ≥2× its stated baseline. Two different channels are sought separately for shape and ingredients; a missing match stays visible. Nizarisaqt and MoreNizarisaqt are separate channels from the same creator.</p>
 <div id="ideas-grid">{''.join(card(i) for i in D['ideas'])}</div><div class="pagination"><button id="prev-page" type="button">← Previous ideas</button><span id="page-label"></span><button id="next-page" type="button">Next ideas →</button></div></section>'''

compositions=[
 ('Two-person introduction','Portrait / compelling scene','a6a1GihedNA','FUTHXQcatr0','One face establishes the host, a second torso or face carries the reveal; shallow room depth and one identity label.','2, 5–7, 49'),
 ('Physical answer boards','Graphic choice / social tension','aaf3Q1mqxdg','XhGbk68II-Q','Opposed red/green blocks put the disagreement below readable faces; shoot both reactions at equal scale.','8–10, 71–77'),
 ('Budget versus premium split','Comparison / amplified reality','T2MSUmQmiWU','InFfrfaSuRI','Match subject scale across the split; spend labels are small and supported by actual receipts. The examples mix a price game and an upgrade.','36, 64, 67, 69, 97'),
 ('Before and after','Transformation / progression','9IT6t8Pzk7w','3jcmI8cLDGQ','Keep the room axis stable; the desk itself supplies the contrast while the recipient supplies emotion.','41, 52, 60'),
 ('Face beside game or physical evidence','Compelling scene / reaction','pRIHc5C4Q_A','UR45HsG-mY8','A close face occupies one side; the specific consequence or choice occupies the other; familiar UI explains the bridge.','11–22, 81–90'),
 ('Game versus real object','Comparison / product','q8QnRcTleS0','iV8Bx-KQYPc','Match the food, toy or action across halves; preserve silhouette so the difference reads before text.','13, 56, 63, 67, 90'),
 ('Color as the rule','Repetition / product grouping','vqwuXYVl3BY','v_9kXIX9fs4','One color per person or zone turns the rule into the background; products stay in a readable foreground cluster.','23, 40'),
 ('Social screen with a reaction','Social UI / information gap','UXEEWwNp7Us','EB-ljy6cDEk','One comment or clip panel paired with one large reaction; use the real permitted post and avoid invented metrics.','4, 42, 50–52, 58'),
 ('Enclosed-space time challenge','Compelling scene / specific day','jpyNCo-FCHY','Ek5GuBlUC6o','The windshield or doorway frames both people; cramped posture shows the challenge and one time label supplies progress.','31–39, 83, 86'),
 ('One person, one unusual product','Product / scale / curiosity','IOEwIGoYx24','JzZYsOzINsI','Place the object beside the face at comparable visual weight; show the real function, not invented damage.','61–70'),
 ('Unembellished access photo','Portrait / day / location','CZ0Xnpn9f7Y','1sKAiMG6HhE','Natural framing lets a familiar face and an unfamiliar place carry access; no mandatory text or decorative arrow.','1, 3, 91, 94, 100')]
packcards=''
for name,framework,a,b,desc,ids in compositions:
 packcards+=f'<article class="package"><span class="eyebrow">{H(framework)}</span><h3>{H(name)}</h3><p>{H(desc)}</p><p class="fine">Relevant ideas: {ids}. Visual interpretation of the cited source images; view lifts do not isolate thumbnail effectiveness.</p>{refs([E[a],E[b]])}</article>'
shape_rows=''
for shape in dict.fromkeys(i['shape'] for i in D['ideas']):
 group=[i for i in D['ideas'] if i['shape']==shape];ev=list({e['video_id']:e for i in group for e in i['shape_evidence']}.values()); scored=[e for e in ev if e['lift'] is not None];ch={e['channel'] for e in scored if e['lift']>=2}
 shape_rows+=f'<details class="format-row"><summary><span>{H(shape)}</span><small>{len(group)} ideas · {len(ev)} selected examples · {len(ch)} outlier channels</small></summary><p>Proposed shapes: {H(" / ".join(dict.fromkeys(i["title_shape"] for i in group)))}</p><p>Ideas: '+', '.join(f'<a href="#idea-{i["id"]}">#{i["id"]}</a>' for i in group)+f'</p>{refs(ev)}<p class="fine">Selected literal/related format matches from the {len(D['evidence_pool']):,}-video pool, not an exhaustive count of the format on YouTube.</p></details>'
packaging=f'''<section id="packaging" class="chapter"><div class="section-head"><div><span class="eyebrow">02 / Earn the click honestly</span><h2>Packaging</h2></div><p>Title mechanics, visual composition and supporting examples.</p></div><div class="callout"><b>Build from the example's geometry.</b> Match face scale, subject placement, division of the frame and visual contrast, then swap Niz and the relevant episode content. The attached guides add expectation match, an information gap, readable emotion and one dominant subject. <a href="#guides">Applied guidance →</a></div><h3>Composition library</h3><div class="two-grid">{packcards}</div><h3>Title-format library</h3><p>Open a format to compare its examples, channels, view counts, publication dates and score denominators. A strong result for one creator does not validate every ingredient swap.</p>{shape_rows}<p class="fine">CTR, impressions and thumbnail-test winners are unavailable for these public reference channels. No composition is labeled a CTR winner.</p></section>'''

hooks=[('Recognition → unexpected real version','A familiar game mechanic happens in a physical setting.','Show the game and its physical counterpart immediately; establish one changed rule; deliver a small result before widening the challenge.','11–18, 89–90','q8QnRcTleS0'),('Forced choice','Viewers choose before the creator does.','Put both options on screen; allow a short guess window; reveal the consequence and use it to create the next decision.','12, 16–17, 46, 73, 76','UR45HsG-mY8'),('First meeting / missing person','A known voice gains a real face and a new relationship.','Use one familiar cue, show the meeting, then turn it into a shared task rather than an extended greeting.','2, 5–7, 49','a6a1GihedNA'),('Visible consequence','The game action changes something real.','Show the consequence prop in frame before the attempt; trigger it immediately after a loss; keep a score so each round changes the situation.','21–29, 44, 55','pRIHc5C4Q_A'),('Contrast you can test','Two options invite a verdict the viewer can check.','Use the same task, framing and judging criteria on both sides; reveal actual costs after an initial guess.','30, 36, 64, 67, 69, 97','T2MSUmQmiWU'),('Transformation with a deadline','A visible starting problem must become a finished result.','Show the before state and recipient need; identify a deadline; reveal meaningful progress instead of a shopping montage.','14, 40–41, 52, 60','9IT6t8Pzk7w'),('Social disagreement','Two people interpret the same evidence differently.','Start with conflicting answers; let each give one concise reason; resolve with an observable answer or let the unresolved judgment become the point.','4, 8–10, 42, 50–51, 78','aaf3Q1mqxdg'),('Uncertainty in a bounded location','A clear objective is interrupted by a specific unknown.','Show the environment before the scare, establish the task and rules, then preserve enough quiet for a real change to register.','39, 81–86, 89','5hwV95hXSN4')]
creative='<section id="creative" class="chapter"><div class="section-head"><div><span class="eyebrow">03 / Keep a live question</span><h2>Creative</h2></div><p>Practical hook types and ways to carry the episode.</p></div><p>These are proposed IRL adaptations of visible niche formats and the intelligence system. Their effectiveness needs an episode test; the measured moment evidence is in Post-Production.</p><div class="two-grid">'
for name,why,how,ids,ref in hooks:creative+=f'<article class="text-card"><h3>{name}</h3><p><b>Audience question:</b> {why}</p><p>{how}</p><p class="fine">Ideas {ids} · <a href="{E[ref]["url"]}" target="_blank" rel="noopener">Niche reference: {H(E[ref]["title"])}</a></p></article>'
creative+='''</div><h3>Three ways to structure a full episode</h3><div class="three-grid"><article class="text-card"><h4>Rounds with consequences</h4><p>For quizzes, food and crew games: promise → simple first round → harder choice → changed score → final contest. Each result changes the next attempt. Keep one score graphic and remove repeated rules.</p></article><article class="text-card"><h4>A task in the real world</h4><p>For builds, shifts and travel: visible goal → first attempt → real obstacle → revised approach → finished result. Cut transport that changes nothing; keep a person correcting Niz or a decision that changes the route.</p></article><article class="text-card"><h4>Access through a relationship</h4><p>For family and meetups: recognition → shared task → disagreement or surprise → a revealing story → something they accomplish together. A guest introduction earns its length through action.</p></article></div><div class="callout"><b>First-frame contract:</b> The pictured people, object or dilemma should be visible immediately. By 15 seconds the rule and stakes should be clear; by 30 seconds a real attempt should be underway. These are writing targets, not measured universal retention thresholds.</div><h3>Re-hook after each payoff</h3><p>Show what changed, then open the next specific question. Use a harder round, a shrinking budget, a newly revealed clue or a guest taking control. Avoid a new promise that the episode never answers, long resets after a win, and repeated shouting that adds no information.</p></section>'''

creative=creative.replace('</section>',solo_creative+'</section>')

production='<section id="production" class="chapter"><div class="section-head"><div><span class="eyebrow">04 / Spend on what changes the video</span><h2>Production</h2></div><p>Incremental cash, USD. Owned cameras and recording equipment are excluded.</p></div><p>Planning allowances as of September 24, 2026, not live quotes. Totals sum the line items below and exclude Niz’s labor, ongoing salaried crew/editor costs, sponsorship offsets and refundable deposits. Travel assumptions are explicit; add a separate 10–15% contingency after choosing the real route and dates. Guest appearance fees are unconfirmed.</p><div class="two-grid">'
for key,p in D['profiles'].items():
 ids=[i['id'] for i in D['ideas'] if i['production_profile']==key]
 production+=f'<article class="cost-card" id="cost-{key}"><h3>{H(p["name"])}</h3><div class="price">{money(p["low"])}–{money(p["high"])}</div><p class="fine">{H(p["days"])} · {H(p["crew"])}</p><table><caption>Incremental expense breakdown</caption><tbody>'+''.join(f'<tr><th scope="row">{H(name)}</th><td>{money(lo)}–{money(hi)}</td></tr>' for name,lo,hi in p['lines'])+f'</tbody></table><p>{H(p["value"])}</p><p class="fine">Ideas: '+', '.join(f'<a href="#idea-{id}">#{id}</a>' for id in ids)+'</p></article>'
production+='</div><h3>Choose the shoot by what you get from the fixed cost</h3><p>Start with local crew games, food comparisons and physical Roblox recreations. A destination trip should have a named story, booked access and multiple distinct deliverables before airfare is purchased. Do not allocate all travel cost to a single Short or count an expensive ticket as a hook by itself.</p></section>'

production=production.replace('</section>',solo_production+'</section>')

post=f'''<section id="post-production" class="chapter"><div class="section-head"><div><span class="eyebrow">05 / Edit from the measured moments</span><h2>Post-Production</h2></div><p>MoreNizarisaqt retention curves and timestamped decisions.</p></div><p>The source catalogue contains 475 retention curves. This explorer selects 28 relevant videos with annotated moments: guessing games, horror, night shifts, progression and survival. Dashboard pull: September 5, 2026; data through September 3. <a href="../channels/UCvEtdkmA1aR9Tt7iXIiQXbw.html">Open the channel analysis →</a></p><div class="retention-lab"><label for="retention-select">Compare a video</label><select id="retention-select">{''.join(f'<option value="{v["videoId"]}">{H(v["title"])}</option>' for v in D['retention']['cases'])}</select><div id="retention-stats" class="metrics"></div><svg id="retention-chart" viewBox="0 0 1000 330" role="img" aria-labelledby="chart-title chart-desc"><title id="chart-title">Audience retention</title><desc id="chart-desc">Measured watch ratio across video duration. Use the moment buttons below to inspect peaks and drops.</desc></svg><div class="chart-controls"><label>Inspect time<input id="retention-time" type="range" min="0" value="0" step="1"></label><output id="retention-readout" aria-live="polite"></output><a id="retention-watch" href="#" target="_blank" rel="noopener">Watch this timestamp ↗</a><a id="retention-source" href="#">Full source analysis →</a></div><p class="fine">The curve plots the source watch ratio, which can exceed 100% when sections are replayed. Times and 5s/15s/30s values interpolate the available percentage-duration samples; they are not second-by-second event measurements. Green markers are source-tagged peaks; coral markers are source-tagged drops. A tagged drop may still outperform the usual drop at that position.</p><div id="moment-list"></div></div>
 <h3>What to carry into an IRL edit</h3><div class="two-grid"><article class="text-card"><h4>Show the solution, then advance</h4><p>Singer Tower at 6:20 records a sustained rise through five samples (+0.9% of viewers present in the source annotation). Keep the solved state legible. At 6:51, the post-verdict aside has a 2.3× normal stop rate. Test a shorter bridge into the next question.</p><a href="../channels/UCvEtdkmA1aR9Tt7iXIiQXbw/pDlG2tmh0LY.html">Source and caveats →</a></article><article class="text-card"><h4>Keep a strong reaction connected to an outcome</h4><p>The 6:45 Adele verdict in the same video shows a one-sample +5.6% rise among viewers present. At 3:53, a scream transition has a 2.6× normal stop rate. The practical test is a clear verdict followed by the next choice, with reaction length earned by the result.</p><a href="https://www.youtube.com/watch?v=pDlG2tmh0LY&t=405s" target="_blank" rel="noopener">Review the 6:45 moment →</a></article><article class="text-card"><h4>Distinguish a reveal from the reset after it</h4><p>Mining Factory marks the unlock at 6:49 as a peak and the following 6:56 segment as a drop. Preserve the reward and inspect the transition into another purchase or grind. For a real build, reveal the working upgrade before moving on.</p><a href="../channels/UCvEtdkmA1aR9Tt7iXIiQXbw/olRuWh8AFWM.html">Inspect both moments →</a></article><article class="text-card"><h4>Review interruptions and repeated effort</h4><p>Grow a Chicken Fighter flags 7:41 around a subscribe/like aside. Drain Water flags a shop/menu moment at 10:29 and a grind admission at 15:55. Trial cuts should retain the relevant decision while shortening repeated explanation.</p><a href="../channels/UCvEtdkmA1aR9Tt7iXIiQXbw/ceLlgiGLyYw.html">Review the source →</a></article></div>
 <h3>Moment patterns across the channel</h3><p>The source grouped 119 usable moments from 36 of 40 recent analyzed videos. <b>No category had a consistent effect.</b> The adjusted percentage-point values below compare flagged moments with the typical flagged moment of the same kind and video position; they are not a promised lift in overall retention.</p><div class="table-scroll"><table><thead><tr><th>Tagged moment type</th><th>Adjusted median effect</th><th>Moments / videos</th><th>p-value</th><th>Edit implication to test</th></tr></thead><tbody>'''+''.join(f'<tr><th scope="row">{a}</th><td>{b}</td><td>{c}</td><td>{d}</td><td>{e}</td></tr>' for a,b,c,d,e in [('Viewers scrub back','+1.9 pp','26 / 16','.152','Keep the payoff legible; a replay can also signal confusion.'),('Scripted / NPC dialogue','+1.3 pp','13 / 9','.267','Keep dialogue that changes a choice; trim repetitive exposition.'),('Reveal / pull / unlock','+0.8 pp','10 / 8','1.000','Preserve the reveal and shorten the reset afterward.'),('Explaining plan / setup','+0.4 pp','8 / 8','1.000','Show the rule while action begins.'),('Tangent / aside','0.0 pp','19 / 12','1.000','Judge the specific aside; the category alone gives no answer.'),('Shop / menu','−0.2 pp','12 / 10','.774','Keep the purchase decision, compress navigation.'),('Combat / boss','−0.4 pp','13 / 10','.774','Clarify the objective and what each attempt changes.'),('Grind / rebirth admission','−1.9 pp','6 / 6','1.000','Replace repeated effort with progress and a fresh target.'),('Mistake / failure','−2.4 pp','12 / 11','.774','Keep consequences; avoid repeating an unchanged failure.')])+'''</tbody></table></div><p class="fine">Groups are observational and small. First-30-second/coarse/unusable moments were excluded by the source. These are gaming-channel patterns to test in IRL, not established IRL retention laws.</p><h3>Editor handoff</h3><ol><li>Mark the promised payoff and the next unanswered question in every scene.</li><li>Review 15 seconds on each side of a flagged moment; distinguish confusing action, a rewind, an ad break and a spent payoff.</li><li>Make one specific proposed change, keep the original cut, and record what would support or disprove it.</li><li>After release, compare early retention and relative performance at matched video positions; do not attribute a whole-video result to one cut.</li></ol></section>'''

shortsection='<section id="shorts-strategy" class="chapter"><div class="section-head"><div><span class="eyebrow">06 / Turn one beat into a complete Short</span><h2>Shorts Strategy</h2></div><p>Creators in Niz’s niche: Foltyn and Lana’s Life.</p></div><p>Live public Shorts shelves checked September 24, 2026: 48 visible Shorts per channel. Counts are rounded lifetime views, not engaged views, retention or conversion to long-form. Sample medians: Foltyn 8.15M; Lana’s Life 2.10M. Ratios compare only this visible shelf, are not age-adjusted outlier scores, and do not prove why a Short worked.</p><div class="two-grid">'
for f in D['shorts']['formats']:
 shortsection+=f'<article class="short-card"><h3>{H(f["name"])}</h3><p><b>Hook:</b> {H(f["hook"])}</p><p><b>Niz version:</b> {H(f["niz"])}</p><p><b>Need / cost:</b> {H(f["production"])}</p><p class="fine">Proposed timing: {H(f["beats"])}</p><ul class="short-examples">'
 for e in f['examples']:shortsection+=f'<li><a href="{e["url"]}" target="_blank" rel="noopener">{H(e["title"])}</a><small>{"Foltyn" if e["channel"]=="foltynfamily" else "Lana’s Life"} · {fmt(e["views_rounded"])} lifetime views · {e["visible_sample_ratio"]:.2f}× visible-shelf median</small></li>'
 shortsection+='</ul><p class="fine">Pull from ideas '+', '.join(f'<a href="#idea-{id}">#{id}</a>' for id in f['ideas'])+'</p></article>'
shortsection+='''</div><h3>Four-week test, attached to real shoots</h3><div class="table-scroll"><table><thead><tr><th>Week</th><th>Production plan</th><th>What to compare</th></tr></thead><tbody><tr><th>1</th><td>Film 2 self-contained Shorts on a local crew-game day.</td><td>A question-first opening versus an action-first opening on comparable rounds.</td></tr><tr><th>2</th><td>Make 2 food or physical-game Shorts while filming the related episode.</td><td>Clear real-world payoff versus a game-to-real-life match cut.</td></tr><tr><th>3</th><td>Repeat the more promising format with a different specific prompt.</td><td>Whether the result repeats without increasing spend.</td></tr><tr><th>4</th><td>Keep the best repeatable format and produce 2 new examples.</td><td>Viewed versus swiped, engaged views, average percentage viewed, subscribers and related-video traffic.</td></tr></tbody></table></div><p>Each Short should make sense without the full episode. Use a related-video link when the long video delivers the same promise; avoid withholding the Short’s entire answer just to force a click. Raw Short views and long-form views are different measures.</p><details><summary>Full 96-Short source sample</summary><div class="table-scroll"><table><thead><tr><th>Creator</th><th>Short</th><th>Rounded lifetime views</th></tr></thead><tbody>'''+''.join(f'<tr><td>{H(s["channel"])}</td><td><a href="{s["url"]}" target="_blank" rel="noopener">{H(s["title"])}</a></td><td>{fmt(s["views_rounded"])}</td></tr>' for s in D['shorts']['sample'])+'</tbody></table></div></details></section>'

legacy=(BASE/'research/original-sections.html').read_text(encoding='utf8')
# Preserve historical material without duplicate navigation IDs or heading hierarchy conflicts.
legacy=re.sub(r'\sid="[^"]*"','',legacy).replace('<h2','<h4').replace('</h2>','</h4>')
legacy=legacy.replace('—',': ')
datasection=f'''<section id="data-analysis" class="chapter"><div class="section-head"><div><span class="eyebrow">07 / Sources, scope and the original research</span><h2>Data Analysis</h2></div><p>Keep the numbers auditable.</p></div><div class="metrics"><div><b>100</b><span>ideas preserved</span></div><div><b>{len(D['evidence_pool']):,}</b><span>unique videos searched</span></div><div><b>{D['coverage']['shape_two_channels']}</b><span>ideas with 2+ outlier channels for shape</span></div><div><b>{D['coverage']['ingredients_two_channels']}</b><span>ideas with 2+ outlier channels for ingredients</span></div></div><p>{D['coverage']['both']} ideas meet the two-channel target on both axes within this pool. Others retain explicit gaps, weaker comparisons or unscored matches. Separate Niz channels share a creator, and Cash/Nico examples share a cast ecosystem, so channel counts do not mean independent audiences. Six adjacent IRL challenge channels broaden the search; their evidence cards explicitly flag the audience transfer.</p>
 <div class="table-scroll"><table><thead><tr><th>Evidence</th><th>Window / denominator</th><th>What it can support</th></tr></thead><tbody><tr><th>Current public reference catalogues</th><td>Imported lifetime-view scores; source notes describe nearby-upload or recent-catalogue baselines. Source pages generally updated September 11.</td><td>Within-channel source scores, not an independently recomputed common baseline. No CTR or private retention.</td></tr><tr><th>MoreNizarisaqt scored uploads</th><td>Source first-28-day / nearby-upload median; availability varies.</td><td>Channel-relative format evidence; keep distinct from lifetime scores.</td></tr><tr><th>Retention explorer</th><td>Stored watch-ratio curves; source pull September 5, through September 3; selected annotations may have earlier pull dates.</td><td>Measured shape and timestamped editorial hypotheses; no causal verdict.</td></tr><tr><th>Shorts shelves</th><td>96 visible public Shorts, September 24; rounded lifetime counts.</td><td>Current niche examples and visible-sample comparisons; no age control or conversion proof.</td></tr><tr><th>Original ideation forecast</th><td>Main-channel 264,532-view base × historical evidence median; range 0.64–1.40.</td><td>Historical planning heuristic only. It is not an IRL forecast and has not been revalidated.</td></tr></tbody></table></div>
 <h3 id="guides">How the intelligence and attached guides were applied</h3><p>The public intelligence system supplies familiar-plus-mystery, credible stakes and the first-frame promise. The two attached thumbnail documents supply expectation match, one dominant subject, restrained visual groups, contrast, mobile readability and concrete frameworks. The user’s instruction to closely preserve each reference composition controls this revision; guide suggestions inform the adaptation rather than imposing a new generic style.</p><ul><li><a href="../intelligence-system.html">Intelligence-system source</a> and <a href="../intelligence/general.html">general claims</a>: rules are distinguished from observations and theories.</li><li><b>10 Rules of Thumbnails</b>: use the filmed premise, complementary title/visual information and an appropriate facial reaction.</li><li><b>16 Engaging Thumbnail Frameworks</b>: comparison, transformation, portrait, social UI, compelling scene, product and progression appear in the Packaging library.</li></ul>
 <details class="legacy"><summary>Original channel, launch, sequencing and method research</summary><p class="callout">Preserved September 9/10 snapshot. Historical subscriber counts, projections, score denominators and old language below are retained for provenance; use the revised evidence above for decisions.</p>{legacy}</details>
 <details><summary>Original projections for all 100 ideas</summary><p class="fine">Preserved, not recalculated after deduplication. No claim that a new IRL channel reaches the established main channel's baseline.</p><div class="table-scroll"><table><thead><tr><th>Idea</th><th>Historical midpoint</th><th>Historical range</th><th>Historical median lift</th></tr></thead><tbody>'''+''.join(f'<tr><td>#{i["id"]} {H(i["title"])}</td><td>{fmt(i["projected_views"])}</td><td>{fmt(i["projected_range"][0])}–{fmt(i["projected_range"][1])}</td><td>{i["evidence_median_lift"]}×</td></tr>' for i in D['ideas'])+f'''</tbody></table></div></details><div class="downloads"><a href="{SLUG}/strategy-data.json" download>Download revised research JSON</a><a href="{SLUG}/ideas-original-2026-09-10.json" download>Download original ideas JSON</a><a href="{SLUG}/thumbnail-manifest.json" download>Thumbnail manifest</a></div><p class="fine">Thumbnails are generated concepts, not footage of completed episodes. Supporting cast, locations, prices and screenshots require final production verification. Built-in image generation does not expose a model name; GPT Image 2.5 Flare is not certified. No thumbnail CTR or audience test has been run.</p></section>'''

datasection=datasection.rsplit('</section>',1)[0]+solo_data+'</section>'

nav=[('ideation','Ideation'),('packaging','Packaging'),('creative','Creative'),('production','Production'),('post-production','Post-Production'),('shorts-strategy','Shorts Strategy'),('data-analysis','Data Analysis')]
htmlpage=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Nizarisaqt IRL | Creator playbook · Influint</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="{SLUG}/strategy.css?v=solo-formats-v1"></head><body data-study-version="seven-sections-v1" data-solo-version="solo-formats-v1"><a class="skip" href="#ideation">Skip to ideas</a><header class="site"><a href="../index.html" class="brand">INFLUINT</a><a href="../channels/UCVhGR9TU1vfvHXl73uaEiEQ.html">Nizarisaqt channel ↗</a><span>Study revision · 24 Sep 2026</span></header><div class="masthead"><span class="eyebrow">Nizarisaqt IRL / Creator playbook</span><h1>125 ideas for<br>Nizarisaqt IRL.</h1><p>100 original episode concepts plus 25 new videos across five formats Niz can film alone.</p></div><nav class="chapter-nav" aria-label="Study sections">{''.join(f'<a href="#{id}"><span>{n:02}</span>{name}</a>' for n,(id,name) in enumerate(nav,1))}</nav><main>{ideation}{packaging}{creative}{production}{post}{shortsection}{datasection}</main><footer>Nizarisaqt IRL · Working strategy and evidence · September 2026</footer><dialog id="thumbnail-modal" aria-labelledby="thumbnail-title"><form method="dialog"><button aria-label="Close thumbnail">Close ×</button></form><h2 id="thumbnail-title"></h2><img id="thumbnail-full" alt=""><div class="modal-actions"><button id="thumbnail-prev" type="button">← Previous</button><a id="thumbnail-download" download>Download JPG</a><button id="thumbnail-next" type="button">Next →</button></div></dialog><script src="{SLUG}/strategy.js?v=solo-formats-v1" defer></script></body></html>'''
(REPO/'studies'/(SLUG+'.html')).write_text(htmlpage,encoding='utf8')
write= lambda p,x:p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
for i in D['ideas']:i['thumbnail']=TH[i['id']]
write(A/'ideas.json',{'updated':D['updated'],'channel':original['channel'] if (original:=json.loads((A/'ideas-original-2026-09-10.json').read_text(encoding='utf8'))) else '', 'ideas':D['ideas']})
print('Built seven sections, 100 original cards and 25 solo video briefs:',len(htmlpage),'characters')
