import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const stem=path.basename(dir);
const data=JSON.parse(fs.readFileSync(path.join(dir,'packages.json'),'utf8'));
const evidence=JSON.parse(fs.readFileSync(path.join(dir,'evidence.json'),'utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const labels={first:'Test first',next:'Test next',review:'Review format fit'};
const counts=Object.fromEntries(Object.keys(labels).map(k=>[k,data.items.filter(x=>x.group===k).length]));
const asset=s=>`${stem}/${s}`;
const tile=(id,label,value,sub,body)=>`<details class="data-tile" id="${id}"><summary><span class="tile-label">${label}</span><strong>${value}</strong><span class="tile-sub">${sub}</span><span class="disclosure" aria-hidden="true">+</span></summary><div class="tile-body">${body}</div></details>`;
const tiles=[
tile('channel-data','Channel snapshot','188 uploads','41,436 median lifetime views',`<p>Produced long-form uploads, 13 Nov 2020 to 1 Sep 2026. Catalogue captured 4 Sep 2026. Live broadcasts and premieres are excluded by the source rule.</p>${evidence.overview}<p>1.00x means typical lifetime views against nearby uploads by publication date. It is not a CTR, retention rate or forecast.</p>`),
tile('title-data','Formats & titles','1.96x rain format','43 uploads in the strongest established format',`<p>Rain appears in 63 titles at 1.64x median. Any-weather titles are 1.45x (n=98), versus 0.73x without weather (n=90). These are associations across different videos, not the effect of adding a word.</p>${evidence.grammar}<p>TEMU's 3.17x keyword result has only six videos; the 1.54x title-shape result has three. They are different cohorts. The 45 to 75 character band is a reference, not a title-length target.</p>`),
tile('timing-data','Trajectory & cadence','35,060 views','2026 median; cadence signal varies by window',`${evidence.trajectory}<p>Recent 40 uploads: 5 to 9 day gaps have 1.30x median (n=14), versus 0.97x off rhythm (n=26). Across the full catalogue, it is 0.99x (n=58) versus 0.98x (n=129); one upload has no prior gap.</p><p>Runtime is not retention. The under-25-minute band is 0.49x (n=32); 60 minutes or more is 2.13x (n=8), with format and age confounds.</p>`),
tile('comparison-data','Related uploads','Same premise, different results','Useful references, not controlled experiments',`<p>Wendy's, the Appalachians, stone shelters and budget gear offer relevant creative references. Different footage, seasons, upload ages and audiences prevent attributing their score gaps to packaging alone.</p>${evidence.comparisons}<p>The stone-house comparison already includes rain in the 0.77x title. The difference is not simply rain present versus rain absent. Also, July 2026 Appalachian uploads are younger than the shortlist's 180-day screen.</p>`),
tile('candidate-data','Original shortlist','23 packages','8 test first · 12 test next · 3 review format fit',`<p>The source screen used below 0.70x, more than 180 days old, and a format or weather proxy. All 23 are retained for review. The table below preserves that original screen; corrected priorities are shown on the package cards.</p>${evidence.shortlist}<p><b>Corrections:</b> the cheap-gear guide is not a TEMU challenge; the old-dog inflatable-cabin story is not necessarily winter hot-tent content; Rain Forests does not establish rainy weather. Those three are marked Review format fit.</p>`),
tile('engagement-data','Public engagement','5.99% likes / views','Shortlist median, versus 2.32% for 15 breakouts',`<p>Public watch-page pull: 24 Sep 2026. The shortlist median is 0.059919 likes per view (n=23); the comparison median is 0.023244 (n=15), a 2.6x ratio. Within the source's four strong-format buckets, weak uploads are 0.0595 (n=10) versus 0.0232 (n=11) for stronger uploads.</p><p>This suggests an engaged audience among people who clicked. It does not prove strong retention, low CTR, under-distribution or that broader audiences would respond the same way. The format-assignment caveats above also affect that grouped comparison.</p><p>Per-video like counts, denominators and dates are retained in each card's evidence. They come from a later pull than the browse-card view counts.</p>`),
tile('method-data','Method & limits','0 retention curves','No Studio impressions, CTR or first-28-day windows',`<p>Observed public data supports a test queue. It does not establish that packaging caused an upload to underperform.</p><ul><li><b>P1:</b> a related format performs well; check that the candidate genuinely belongs to it.</li><li><b>P2:</b> similar-premise uploads suggest a creative direction; they are not randomized tests.</li><li><b>P3:</b> weather is named in the original title; confirm its actual role in the footage.</li></ul><p>High retention with low views can motivate a packaging test, but there is no measured verdict here. A weak curve calls for investigating the promise and content, not automatically retiring the video.</p><p>All After thumbnails are AI-generated concepts based on the original images. They may reconstruct details. Match people, equipment, setting and weather to the footage before a YouTube test.</p>`),
tile('research-data','Research library','131 cited claims','Open the evidence behind the recommendations',`<p>The source's claim ledger and cross-channel observations remain available below. Their original standing labels do not turn an unmeasured mechanism into a proven result.</p><details class="research-part"><summary>Intelligence citations and caveats</summary>${evidence.research}</details><details class="research-part"><summary>Cross-channel cohort evidence</summary>${evidence.cohort}</details><p><a href="${asset('source-record.html')}">Archived analysis with superseded recommendations</a> · <a href="${asset('source-record.md')}">Archived Markdown</a></p>`)
].join('\n');
function video(c,after){
 const title=after?c.proposedTitle:c.originalTitle;
 const image=after?c.after:c.before;
 return `<div class="package"><div class="package-label ${after?'after':''}"><b>${after?'After':'Before'}</b><span>${after?'Proposed concept':'Original package'}</span></div><a class="thumb ${after?'':'original'}" href="${asset(image)}" target="_blank" rel="noopener" aria-label="Open ${after?'after concept':'original thumbnail'} for ${esc(title)}"><img src="${asset(image)}" alt="${after?'AI-generated thumbnail concept':'Original thumbnail'}: ${esc(title)}" width="1280" height="720" loading="lazy"><span class="duration">${esc(c.duration)}</span></a><div class="video-info"><img class="avatar" src="${asset('channel-avatar.jpg')}" alt="" width="36" height="36" loading="lazy"><div><h3 class="video-title">${esc(title)}</h3><p class="channel-name">Camping with Sam Bananas</p><p class="video-meta" title="${c.views.toLocaleString('en-US')} lifetime views, catalogue 4 Sep 2026">${Math.floor(c.views/1000)}K views · ${esc(c.age)}</p></div></div></div>`;
}
function card(c){
 const date=new Date(c.published).toISOString().slice(0,10);
 return `<article class="comparison" id="video-${c.id}" data-group="${c.group}" data-search="${esc(c.originalTitle+' '+c.proposedTitle+' '+c.id)}"><header class="comparison-head"><span class="number">${String(c.n).padStart(2,'0')}</span><span class="priority ${c.group}">${labels[c.group]}</span><span class="score">${c.outlier.toFixed(2)}x <span>vs nearby uploads</span></span></header><div class="pair">${video(c,false)}${video(c,true)}</div><div class="rationale"><p><b>The hook:</b> ${esc(c.hook)}</p><p>${esc(c.reason)}</p></div><details class="card-evidence"><summary>Evidence & content check</summary><div><p><b>Observed:</b> ${c.views.toLocaleString('en-US')} lifetime views; ${c.outlier.toFixed(2)}x outlier; published ${date}; runtime ${esc(c.duration)}. Catalogue: 4 Sep 2026.</p>${c.engagement?`<p><b>Later engagement pull:</b> ${c.engagement.likes.toLocaleString('en-US')} likes / ${c.engagement.views.toLocaleString('en-US')} views = ${c.engagement.likesPer100}% (24 Sep 2026). Likes are not retention.</p>`:''}<p><b>Content check:</b> ${esc(c.guard)}</p><p><b>Before testing:</b> confirm the opening delivers this promise; inspect impressions, traffic sources, CTR and retention against comparable uploads. The concept image is reconstructed, not a verified footage frame.</p></div></details><div class="card-actions"><a href="https://www.youtube.com/watch?v=${c.id}" target="_blank" rel="noopener">Watch original ↗</a><a href="${asset(c.after)}" download="sam-bananas-${c.id}-concept.jpg">Download After thumbnail ↓</a></div></article>`;
}
const ordered=[...data.items].sort((a,b)=>['first','next','review'].indexOf(a.group)-['first','next','review'].indexOf(b.group)||a.n-b.n);
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="23 before-and-after packaging concepts for Camping with Sam Bananas, grounded in the channel's observed performance."><title>Sam Bananas · Repackaging Review | Influint</title><link rel="icon" href="${asset('influint-mark.png')}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&family=Roboto:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${asset('study.css')}"></head>
<body><a class="skip" href="#packages">Skip to before & after</a><div class="wrap"><header class="site"><a class="brand" href="../index.html"><img src="${asset('influint-mark.png')}" width="28" height="28" alt=""><span>influint<span class="brand-divider"> / </span><span class="brand-sub">channel intelligence</span></span></a><a class="back-link" href="../channels/UCDKQlnsHrUcrYH3B9v7XUAg.html">Channel report ↗</a></header><main><header class="hero"><div class="channel-heading"><img src="${asset('channel-avatar.jpg')}" alt="Camping with Sam Bananas channel profile" width="48" height="48"><div><p>Camping with Sam Bananas</p><span>@campingwithsambananas · 73K subscribers at capture</span></div></div><h1>Same videos.<br><span>A clearer reason to click.</span></h1><p class="lede">23 before-and-after packages, built around the channel's rain camps, unusual shelters and outdoor stories.</p><div class="hero-bottom"><p>Repackaging review · 24 September 2026</p><nav aria-label="Study sections"><a href="#evidence">The data</a><a href="#packages">Before & after</a><a href="#test-plan">Test plan</a></nav></div></header>
<section id="evidence" aria-labelledby="data-heading"><div class="section-head"><h2 id="data-heading">The data, at a glance</h2><button class="text-button" id="toggle-data" type="button" hidden>Expand all data</button></div><p class="section-note">Open a tile for the full numbers and their limits. Public observations guide these proposals; no uplift has been measured.</p><div class="data-grid">${tiles}</div></section>
<section id="packages" aria-labelledby="packages-heading"><div class="section-head"><h2 id="packages-heading">Before & after</h2><span class="count" id="result-count" role="status" aria-live="polite">23 videos</span></div><p class="section-note">Compare each original with its proposed title and AI thumbnail concept. Both show the same recorded views, duration and upload age for a fair visual comparison.</p><div class="toolbar" id="toolbar" hidden><div class="filters" role="group" aria-label="Filter packaging priority"><button type="button" data-filter="all" aria-pressed="true">All 23</button><button type="button" data-filter="first" aria-pressed="false">Test first ${counts.first}</button><button type="button" data-filter="next" aria-pressed="false">Test next ${counts.next}</button><button type="button" data-filter="review" aria-pressed="false">Review fit ${counts.review}</button></div><label class="search"><span class="sr-only">Search videos</span><input id="search" type="search" placeholder="Search videos…" autocomplete="off"></label></div><p class="empty" id="empty" hidden>No videos match. <button type="button" id="reset">Clear filters</button></p><div id="comparisons">${ordered.map(card).join('\n')}</div></section>
<section class="test-plan" id="test-plan" aria-labelledby="test-heading"><h2 id="test-heading">Start with a small, measurable test</h2><ol><li><b>Validate the promise.</b> Check actual footage and the opening before using a concept. Replace reconstructed details with faithful source frames where needed.</li><li><b>Start with the eight strongest candidates.</b> Compare the rain, hot-tent and tarp uploads with similar videos in Studio. Keep the tutorial, old-dog story and Hawaii trip in a separate format review.</li><li><b>Keep the original as a control.</b> Where available, use YouTube's title-and-thumbnail A/B testing. Judge the reported watch-time result; low sample volume may leave a test inconclusive. <a href="https://support.google.com/youtube/answer/16391400?hl=en" target="_blank" rel="noopener">YouTube's testing guidance ↗</a></li><li><b>Record what changed.</b> Log the package, test dates, impressions, traffic mix, CTR, watch time and retention. Do not treat an increase in lifetime views as proof that the new package won.</li></ol></section>
</main><footer><span>Influint · Channel Intelligence</span><div><a href="${stem}.md">Study notes</a><a href="${asset('packages.json')}">Package data</a><a href="${asset('source-record.html')}">Source archive</a><a href="#top">Back to top ↑</a></div></footer></div><script src="${asset('study.js')}" defer></script></body></html>`;
fs.writeFileSync(path.join(dir,'..',stem+'.html'),html.replace('<body>','<body id="top">'));
const md=`# Camping with Sam Bananas: repackaging review\n\nUpdated 24 September 2026. Catalogue 4 September 2026; 188 produced uploads.\n\nThe current web study keeps the original data in expandable tiles and compares all 23 packages with identical observed browse metadata. After images are AI-generated concepts, not actual footage or tested outcomes.\n\n## Evidence and limits\n\n- Rain format: 1.96x median (n=43). Rain keyword: 1.64x (n=63). Any weather: 1.45x (n=98), versus no weather 0.73x (n=90).\n- 41,436 median lifetime views; 37 uploads at 2x or more; 36 below 0.5x.\n- No Studio CTR, impressions, first-28-day windows or retention curves. Likes per view is not retention.\n- Similar-location uploads are observational comparisons, not natural experiments proving packaging effects.\n- The budget tutorial, old-dog cabin trip and Hawaii road trip have weak or invalid format proxies; review fit separately. Rain Forests does not establish rain weather.\n\n## Package proposals\n\n`+ordered.map(c=>`### ${c.n}. ${c.proposedTitle}\n\nPriority: ${labels[c.group]}\n\nBefore: ${c.originalTitle}\n\nObserved: ${c.views.toLocaleString('en-US')} views; ${c.outlier}x; ${c.duration}.\n\n${c.reason}\n\nContent check: ${c.guard}\n\n[Before thumbnail](${stem}/${c.before}) · [After concept](${stem}/${c.after}) · [Original video](https://www.youtube.com/watch?v=${c.id})\n`).join('\n')+`\n## Test plan\n\nValidate footage and the opening, preserve the original control, and use YouTube's native title/thumbnail test where available. Evaluate watch time and traffic context; accept inconclusive outcomes. [YouTube guidance](https://support.google.com/youtube/answer/16391400?hl=en).\n\nOriginal tables and citations: [evidence data](${stem}/evidence.json). Superseded recommendations remain in the [source archive](${stem}/source-record.md).\n`;
fs.writeFileSync(path.join(dir,'..',stem+'.md'),md);
console.log(`Built ${data.items.length} comparisons, ${Object.keys(evidence).length} evidence groups.`);
